import test from "node:test";
import assert from "node:assert/strict";
import { closeTabsForWebspace, recreateWebspaceIdentity, removeWebspaceIdentity, updateWebspaceIdentity } from "../src/lifecycle.js";
function browserMock({failOldIdentityRemoval=false}={}){const calls=[];const api={tabs:{async query(q){calls.push(["tabs.query",q]);return[{id:1},{id:2}]},async remove(ids){calls.push(["tabs.remove",ids])}},contextualIdentities:{async create(input){calls.push(["identity.create",input]);return{cookieStoreId:"new-store",...input}},async remove(id){calls.push(["identity.remove",id]);if(failOldIdentityRemoval&&id==="old-store")throw new Error("remove failed");return{cookieStoreId:id}},async update(id,input){calls.push(["identity.update",id,input]);return{cookieStoreId:id,...input}}}};return{api,calls}}
const webspace={cookieStoreId:"old-store",name:"Work",color:"blue",icon:"briefcase"};
test("Close & Forget lifecycle closes managed tabs before removing the identity",async()=>{const{api,calls}=browserMock();const r=await removeWebspaceIdentity(api,webspace);assert.equal(r.closedTabs,2);assert.deepEqual(calls,[["tabs.query",{cookieStoreId:"old-store"}],["tabs.remove",[1,2]],["identity.remove","old-store"]]);});
test("reset creates replacement identity before removing the old identity",async()=>{const{api,calls}=browserMock();const r=await recreateWebspaceIdentity(api,webspace);assert.equal(r.identity.cookieStoreId,"new-store");assert.equal(calls[0][0],"identity.create");assert.equal(calls.at(-1)[1],"old-store");});
test("reset rolls back the new identity when old-identity removal fails",async()=>{const{api,calls}=browserMock({failOldIdentityRemoval:true});await assert.rejects(()=>recreateWebspaceIdentity(api,webspace),/remove failed/);assert.ok(calls.some(c=>c[0]==="identity.remove"&&c[1]==="new-store"));});
test("appearance updates use Firefox contextual identity update",async()=>{const{api,calls}=browserMock();await updateWebspaceIdentity(api,webspace,{name:"Work",color:"purple",icon:"tree"});assert.deepEqual(calls[0],["identity.update","old-store",{name:"Work",color:"purple",icon:"tree"}]);});
test("closing an empty Webspace does not request tab removal",async()=>{const calls=[];const api={tabs:{async query(){return[]},async remove(ids){calls.push(ids)}}};assert.equal(await closeTabsForWebspace(api,"store"),0);assert.equal(calls.length,0);});
