import { applyAccent, glyphFor, iconLabelFor } from "./identity.js";

let state = null;
let assignmentSearch = "";
let assignmentFilter = "all";

async function send(type, payload = {}) { return browser.runtime.sendMessage({ type, ...payload }); }
function sortedWebspaces(config) { return Object.values(config.webspaces ?? {}).sort((a,b)=>{ if (a.temporary !== b.temporary) return a.temporary ? 1 : -1; if (a.builtIn !== b.builtIn) return a.builtIn ? -1 : 1; return a.name.localeCompare(b.name); }); }
function plural(count, singular, pluralValue = `${singular}s`) { return `${count} ${count === 1 ? singular : pluralValue}`; }
function webspaceName(id) { return state?.config?.webspaces?.[id]?.name ?? id ?? "Unknown Webspace"; }
function setTextStatus(selector, text, error=false) { const node=document.querySelector(selector); node.textContent=text??""; node.dataset.state=error?"error":"ok"; }
function fillSelect(select, options, selectedValue=null) { select.replaceChildren(); for (const {value,label} of options) { const option=document.createElement("option"); option.value=value; option.textContent=label; option.selected=value===selectedValue; select.append(option); } }
function appearanceOptions() { const colors=(state?.appearance?.colors??[]).map((e)=>({value:e.color,label:e.color})); const icons=(state?.appearance?.icons??[]).map((e)=>({value:e.icon,label:e.icon})); return {colors,icons}; }
function webspaceOptions() { return sortedWebspaces(state.config).map((space)=>({value:space.id,label:space.temporary?`${space.name} · Temporary`:space.name})); }

function updateSummary() {
  const config=state.config, webspaces=sortedWebspaces(config), rules=config.userRules??[], enabled=config.routingEnabled!==false;
  const routingStatus=document.querySelector("#routing-status"); routingStatus.dataset.routingState=enabled?"on":"paused"; routingStatus.querySelector("span:last-child").textContent=enabled?"Routing on":"Routing paused";
  document.querySelector("#webspace-summary").textContent=plural(webspaces.length,"Webspace");
  document.querySelector("#tab-summary").textContent=plural(state.activity?.totalManagedTabs??0,"managed tab");
  document.querySelector("#assignment-summary").textContent=plural(rules.length,"assignment");
  document.querySelector("#webspace-count").textContent=plural(webspaces.length,"Webspace");
  const conflicts=state.conflicts??[]; const conflictSummary=document.querySelector("#conflict-summary"); conflictSummary.textContent=conflicts.length?plural(conflicts.length,"conflict"):"No conflicts"; conflictSummary.dataset.state=conflicts.length?"warning":"ok";
}

function field(label, control) { const wrapper=document.createElement("label"); wrapper.className="field"; const text=document.createElement("span"); text.textContent=label; wrapper.append(text,control); return wrapper; }

function buildWebspaceCard(webspace) {
  const card=document.createElement("article"); card.className="card"; card.dataset.webspaceId=webspace.id; applyAccent(card,webspace);
  const header=document.createElement("div"); header.className="space-card-header";
  const emblem=document.createElement("span"); emblem.className="space-emblem"; emblem.setAttribute("aria-hidden","true"); emblem.textContent=glyphFor(webspace); applyAccent(emblem,webspace);
  const copy=document.createElement("div"); copy.className="space-card-copy"; const title=document.createElement("h3"); title.textContent=webspace.name; const kind=document.createElement("div"); kind.className="kind"; kind.textContent=webspace.temporary?"Temporary Webspace":iconLabelFor(webspace); copy.append(title,kind); header.append(emblem,copy);
  const description=document.createElement("p"); description.className="space-description"; description.textContent=webspace.description||(webspace.builtIn?"Built-in provider identity":"Custom browsing identity");
  const stats=document.createElement("div"); stats.className="space-stats"; const tabCount=state.activity?.tabCounts?.[webspace.id]??0; const assignmentCount=(state.config.userRules??[]).filter((r)=>r.webspaceId===webspace.id).length;
  for (const label of [plural(tabCount,"tab"),plural(assignmentCount,"rule"),webspace.locked?"Locked":"Editable"]) { const pill=document.createElement("span"); pill.className="mini-pill"; pill.textContent=label; stats.append(pill); }
  const actions=document.createElement("div"); actions.className="space-card-actions";
  const open=document.createElement("button"); open.className="glz-button"; open.type="button"; open.textContent="Open Webspace ↗"; open.addEventListener("click",()=>send("webspaces:open",{webspaceId:webspace.id}));
  const duplicate=document.createElement("button"); duplicate.className="glz-button"; duplicate.type="button"; duplicate.title="Duplicate Webspace configuration into a fresh isolated identity"; duplicate.textContent="Duplicate"; duplicate.addEventListener("click",async()=>{ try { const result=await send("webspaces:duplicate",{webspaceId:webspace.id}); state=result; setTextStatus("#create-status",`${webspace.name} duplicated. Copied rules are disabled until reviewed.`); renderAll(); } catch(error) { setTextStatus("#create-status",error.message,true); } });
  actions.append(open,duplicate);
  const settings=document.createElement("details"); settings.className="space-settings"; const summary=document.createElement("summary"); summary.textContent="Manage Webspace"; settings.append(summary);
  const editGrid=document.createElement("div"); editGrid.className="space-edit-grid";
  const name=document.createElement("input"); name.className="glz-input"; name.value=webspace.name; name.maxLength=48; name.disabled=webspace.builtIn||webspace.locked;
  const descriptionInput=document.createElement("input"); descriptionInput.className="glz-input"; descriptionInput.value=webspace.description??""; descriptionInput.maxLength=180; descriptionInput.disabled=webspace.locked;
  const color=document.createElement("select"); color.className="glz-select"; fillSelect(color,appearanceOptions().colors,webspace.color); color.disabled=webspace.locked;
  const icon=document.createElement("select"); icon.className="glz-select"; fillSelect(icon,appearanceOptions().icons,webspace.icon); icon.disabled=webspace.locked;
  const nameField=field("Name",name); if(webspace.builtIn) nameField.title="Built-in Webspace names are fixed."; const descField=field("Description",descriptionInput); descField.classList.add("field-wide"); editGrid.append(nameField,field("Color",color),field("Icon",icon),descField);
  const row=document.createElement("div"); row.className="space-action-row";
  const save=document.createElement("button"); save.type="button"; save.className="glz-button primary"; save.textContent="Save appearance"; save.disabled=webspace.locked; save.addEventListener("click",async()=>{ try { const result=await send("webspaces:update",{webspaceId:webspace.id,webspace:{name:name.value,description:descriptionInput.value,color:color.value,icon:icon.value}}); state=result; renderAll(); } catch(error) { setTextStatus("#create-status",error.message,true); } });
  const lock=document.createElement("button"); lock.type="button"; lock.className="glz-button"; lock.textContent=webspace.locked?"Unlock":"Lock"; lock.disabled=webspace.temporary===true; lock.addEventListener("click",async()=>{ const result=await send("webspaces:set-lock",{webspaceId:webspace.id,locked:!webspace.locked}); state=result; renderAll(); });
  const reset=document.createElement("button"); reset.type="button"; reset.className="glz-button danger"; reset.textContent="Reset identity"; reset.disabled=webspace.locked; reset.addEventListener("click",async()=>{ if(!confirm(`Reset ${webspace.name}? Its open tabs will close and Firefox will replace the underlying contextual identity. Site assignments are preserved, but website login/session state in this Webspace will not be preserved.`))return; try{const result=await send("webspaces:reset",{webspaceId:webspace.id});state=result;renderAll();}catch(error){setTextStatus("#create-status",error.message,true);} });
  row.append(save,lock,reset);
  if(!webspace.builtIn){const remove=document.createElement("button");remove.type="button";remove.className="glz-button danger";remove.textContent=webspace.temporary?"Close & Forget":"Delete";remove.disabled=webspace.locked;remove.addEventListener("click",async()=>{const verb=webspace.temporary?"Close & Forget":"Delete";if(!confirm(`${verb} ${webspace.name}? Its managed tabs will close, the underlying Firefox contextual identity will be removed, and its explicit assignments will be removed. GoreeCloud Webspaces will not claim deletion beyond what Firefox confirms through its available APIs.`))return;try{const result=await send(webspace.temporary?"webspaces:close-forget":"webspaces:delete",{webspaceId:webspace.id});state=result;renderAll();}catch(error){setTextStatus("#create-status",error.message,true);}});row.append(remove);}
  settings.append(editGrid,row); card.append(header,description,stats,actions,settings); return card;
}

function renderWebspaces(){const grid=document.querySelector("#webspace-grid");grid.replaceChildren();for(const webspace of sortedWebspaces(state.config))grid.append(buildWebspaceCard(webspace));}
function conflictKeys(){return new Set((state.conflicts??[]).map((c)=>c.key));}
function filteredRules(){const query=assignmentSearch.trim().toLowerCase(),conflicts=conflictKeys();return(state.config.userRules??[]).filter((rule)=>{const target=webspaceName(rule.webspaceId).toLowerCase();const searchMatch=!query||rule.value.includes(query)||target.includes(query)||rule.kind.includes(query);if(!searchMatch)return false;if(assignmentFilter==="enabled")return rule.enabled!==false;if(assignmentFilter==="disabled")return rule.enabled===false;if(assignmentFilter==="conflict")return conflicts.has(`${rule.kind}:${rule.value}`);return true;});}

function renderAssignments(){
  const list=document.querySelector("#assignment-list");list.replaceChildren();const rules=filteredRules();document.querySelector("#no-assignments").hidden=rules.length>0||(state.config.userRules??[]).length>0;const conflicts=conflictKeys(),targets=webspaceOptions();
  for(const rule of rules){const row=document.createElement("div");row.className="assignment";row.dataset.conflict=conflicts.has(`${rule.kind}:${rule.value}`)?"true":"false";
    const value=document.createElement("input");value.className="glz-input";value.value=rule.value;value.setAttribute("aria-label","Assignment hostname");
    const kind=document.createElement("select");kind.className="glz-select";fillSelect(kind,[{value:"domain",label:"Domain + subdomains"},{value:"exact",label:"Exact hostname"}],rule.kind);
    const target=document.createElement("select");target.className="glz-select";fillSelect(target,targets,rule.webspaceId);
    const enabled=document.createElement("label");enabled.className="rule-enabled";const checkbox=document.createElement("input");checkbox.type="checkbox";checkbox.checked=rule.enabled!==false;checkbox.setAttribute("aria-label",`Enable ${rule.value}`);enabled.append(checkbox);
    const actions=document.createElement("div");actions.className="assignment-actions";const save=document.createElement("button");save.type="button";save.className="glz-button";save.textContent="Save";save.addEventListener("click",async()=>{try{state=await send("webspaces:update-assignment",{ruleId:rule.id,assignment:{value:value.value,kind:kind.value,webspaceId:target.value,enabled:checkbox.checked}});setTextStatus("#assignment-status",`Updated ${value.value}.`);renderAll();}catch(error){setTextStatus("#assignment-status",error.message,true);}});const remove=document.createElement("button");remove.type="button";remove.className="glz-button danger";remove.textContent="Remove";remove.addEventListener("click",async()=>{try{state=await send("webspaces:remove-assignment",{ruleId:rule.id});renderAll();}catch(error){setTextStatus("#assignment-status",error.message,true);}});actions.append(save,remove);row.append(value,kind,target,enabled,actions);list.append(row);}
}

function renderComposerOptions(){const{colors,icons}=appearanceOptions();fillSelect(document.querySelector("#new-color"),colors,colors.find(i=>i.value==="blue")?.value??colors[0]?.value);fillSelect(document.querySelector("#new-icon"),icons,icons.find(i=>i.value==="circle")?.value??icons[0]?.value);fillSelect(document.querySelector("#assignment-webspace"),webspaceOptions());}
function renderAll(){updateSummary();document.querySelector("#routing-enabled").checked=state.config.routingEnabled!==false;renderComposerOptions();renderWebspaces();renderAssignments();}
async function refresh(){state=await send("webspaces:get-state");renderAll();}

document.querySelector("#routing-enabled").addEventListener("change",async(event)=>{state=await send("webspaces:set-routing",{enabled:event.target.checked});renderAll();});
document.querySelector("#create-webspace").addEventListener("submit",async(event)=>{event.preventDefault();setTextStatus("#create-status","Creating…");try{const result=await send("webspaces:create",{open:false,webspace:{name:document.querySelector("#new-name").value,description:document.querySelector("#new-description").value,color:document.querySelector("#new-color").value,icon:document.querySelector("#new-icon").value,temporary:document.querySelector("#new-temporary").checked}});state=result;event.target.reset();setTextStatus("#create-status",result.webspace.temporary?"Temporary Webspace created and opened.":"Webspace created.");renderAll();}catch(error){setTextStatus("#create-status",error.message,true);}});
document.querySelector("#add-assignment").addEventListener("submit",async(event)=>{event.preventDefault();try{state=await send("webspaces:add-assignment",{assignment:{value:document.querySelector("#assignment-hostname").value,kind:document.querySelector("#assignment-kind").value,webspaceId:document.querySelector("#assignment-webspace").value,enabled:true}});event.target.reset();setTextStatus("#assignment-status","Assignment added.");renderAll();}catch(error){setTextStatus("#assignment-status",error.message,true);}});
document.querySelector("#assignment-search").addEventListener("input",(event)=>{assignmentSearch=event.target.value;renderAssignments();});
document.querySelector("#assignment-filter").addEventListener("change",(event)=>{assignmentFilter=event.target.value;renderAssignments();});
document.querySelector("#routing-tester").addEventListener("submit",async(event)=>{event.preventDefault();const result=document.querySelector("#test-result");result.replaceChildren();try{const analysis=await send("webspaces:explain-url",{url:document.querySelector("#test-url").value});const card=document.createElement("div");card.className="decision-card";const title=document.createElement("strong");const destination=analysis.decision.webspaceId?webspaceName(analysis.decision.webspaceId):"Normal Firefox";title.textContent=`${analysis.hostname??"Unsupported URL"} → ${destination}`;const reason=document.createElement("span");reason.textContent=`Reason: ${analysis.decision.reason}${Number.isFinite(analysis.decision.priority)?` · priority ${analysis.decision.priority}`:""}`;card.append(title,reason);if(analysis.candidates?.length){const list=document.createElement("div");list.className="candidate-list";for(const candidate of analysis.candidates){const row=document.createElement("div");row.className="candidate-row";row.dataset.selected=candidate.selected?"true":"false";const marker=document.createElement("span");marker.textContent=candidate.selected?"✓":"·";const copy=document.createElement("span");copy.textContent=`${candidate.value??"default"} → ${candidate.webspaceId?webspaceName(candidate.webspaceId):"Normal Firefox"}`;const priority=document.createElement("span");priority.textContent=String(candidate.priority);row.append(marker,copy,priority);list.append(row);}card.append(list);}result.append(card);}catch(error){result.textContent=error.message;}});
document.querySelector("#export-config").addEventListener("click",async()=>{try{const{portable}=await send("webspaces:export-config");const blob=new Blob([`${JSON.stringify(portable,null,2)}\n`],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`goreecloud-webspaces-${new Date().toISOString().slice(0,10)}.json`;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setTextStatus("#portability-status","Configuration exported. Cookies and active login sessions were not included.");}catch(error){setTextStatus("#portability-status",error.message,true);}});
document.querySelector("#import-config").addEventListener("change",async(event)=>{const[file]=event.target.files??[];if(!file)return;try{const portable=JSON.parse(await file.text());if(!confirm("Import this configuration? New custom Webspaces will be created as fresh isolated identities. Existing cookies and login sessions are not imported."))return;const result=await send("webspaces:import-config",{portable});state=result;const summary=result.summary;setTextStatus("#portability-status",`Imported ${plural(summary.createdWebspaces,"Webspace")} and ${plural(summary.importedAssignments,"assignment")}; skipped ${summary.skippedAssignments} conflicting or unavailable assignments.`);renderAll();}catch(error){setTextStatus("#portability-status",error.message,true);}finally{event.target.value="";}});
refresh().catch((error)=>{setTextStatus("#create-status",error.message,true);});
